# on:
#   schedule:  # auto run github action
#     # set auto run time
#     # UTC time 
#     # zh-timm = UTC - 8 
#     #         0:00 - 8  
#     - corn: '1 16 * * *'  
 
on: [push] 

jobs:
  create_issues_action:
    runs-on: ubuntu-latest
    name: create issues action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: create issues action  
        uses: ./  # use an action in the roor diectory 
        with:  # 传参的
          token: ${{ secrets.TOKEN }}
      # Use the output from the `hello` step
      # - name: Get the output time
      #   run: echo "The time was ${{ steps.hello.outputs.time }}"